### ISSUE TITLE
Email Verification and HTML mail templates

### ISSUE THREAD

**Issue by jasondavidcarr** [maxtoroq/MvcAccount#11]
Hi maxtoroq, I started implementing MvcAccount for use on the new LaunchBox Games Database website here: http://gamesdb.launchbox-app.com.

It's been great and is working really well so far, so thank you very much. The only missing pieces at this point are registration and HTML email messages.

Registration I've been able to implement myself, but it's been somewhat of a challenge primarily due to the use of internal classes. In order to make use of updates, I'd rather not copy the code into my project and tweak it there; I'd rather continue to use the Nuget packages, but the internal classes are making it a tad bit difficult. How would you suggest I send the email out to verify the user's email after registration?

Also per the emails, I'd like to figure out how to make them HTML-driven. I think it'd be easy if I were somehow able to override the IAccountContext.RenderEmailView method, but it's internal so I don't see an easy way to do that. Would you have a recommended solution for that?

Again thank you very much for this project and any help you can provide.

Thanks,
Jason

**Comment by maxtoroq** [comment]
@jasondavidcarr 
About registration, see #10.

About verification, there's already a controller for email verification (Email/Verify), the problem is there's no public way to create the URL for that controller. If you don't want to copy the `VerificationData` class to your project you can use reflection. In the future I might provide a service for it, if I come up with a good design.

About sending email, you can provide HTML views for every email template (using the views override mechanism as explained in the documentation), but you need to set `IsBodyHtml` before sending. For that I've added the `MailService` class, you have to checkout the latest code and build it yourself to use it.
